/**
 * The approved Drishya wordmark (brand/source/drishya-logo-original.png).
 * Never redraw it: the files are generated by brand/build_brand.py.
 * `dark` (default) is for this site's dark background: only the black/grey
 * ink is lightened, both blues are untouched. `light` is the original colours.
 */
export function DrishyaLogo({
  variant = "dark",
  className = "h-11 w-auto",
}: {
  variant?: "dark" | "light";
  className?: string;
}) {
  const src = variant === "dark" ? "/brand/drishya-logo-dark.png" : "/brand/drishya-logo-transparent.png";
  // Plain <img>: the site is a static export, so next/image optimisation is unavailable.
  // eslint-disable-next-line @next/next/no-img-element
  return <img src={src} alt="Drishya" width={960} height={428} className={className} decoding="async" />;
}
