/**
 * Single source of truth for every scientific statement on the site.
 *
 * Everything here is transcribed from the project's research study
 * ("I am considering developing the following project_.pdf"). That study is a
 * literature review + proposed design: no experiments have been run by the
 * project team yet. Every value therefore carries an evidence tag:
 *
 *   lit       – reported by a cited third-party study / FSSAI / vendor listing
 *   proposed  – part of the project's proposed design (not yet built or tested)
 *   sim       – generated by this website for demonstration only
 *   concept   – illustrative visualization of a mechanism, not measured
 *
 * If you add content, add it here with a tag. Do not add numbers that are not
 * in the research document.
 */

export type Evidence = "lit" | "proposed" | "sim" | "concept";

export const EVIDENCE: Record<Evidence, { label: string; short: string; desc: string }> = {
  lit: {
    label: "Literature value",
    short: "LIT",
    desc: "Reported by a cited third-party study, FSSAI release or vendor listing. Not measured by this project.",
  },
  proposed: {
    label: "Proposed design",
    short: "PROPOSED",
    desc: "Part of the project's planned design. Not yet built or validated.",
  },
  sim: {
    label: "Simulated demonstration",
    short: "SIMULATED",
    desc: "Generated in your browser for illustration. The website does not measure anything.",
  },
  concept: {
    label: "Conceptual visualization",
    short: "CONCEPT",
    desc: "An illustrative picture of a mechanism described in the literature. Not to scale, not measured.",
  },
};

export const BRAND = {
  name: "NanoFood",
  suffix: "Kit",
  workingNameNote: "Working name — replace in src/content/research.ts",
  title:
    "Development of a Portable Nano-Engineered Rapid Food Testing Kit for On-Site Detection of Food Adulterants and Contaminants",
  headline: "Detect. Analyze. Protect.",
  sub: "Portable Nano-Engineered Rapid Food Testing",
  description:
    "A proposed handheld reader and disposable paper-microfluidic cartridge that screens milk and spices for common adulterants in minutes — using nanoparticle colorimetry, graphene-based electrochemistry and an ESP32 + smartphone readout.",
  status: "Research & design stage — prototype not yet built",
};

/* ------------------------------------------------------------------ */
/* Problem context                                                     */
/* ------------------------------------------------------------------ */

export const FSSAI_2425 = {
  tested: 170535,
  unsafe: 7945,
  substandard: 22516,
  reportedNonConforming: "~20%",
  source: "FSSAI enforcement data 2024–25 [1]",
  evidence: "lit" as Evidence,
};

export const LAB_LIMITS = [
  { k: "24–72 h", v: "Typical lab turnaround", ref: "[1]" },
  { k: "₹500–25,000", v: "Per consumer test at a lab", ref: "[1]" },
  { k: "259 + 24", v: "NABL-accredited + referral labs nationwide", ref: "[6]" },
  { k: "88 + 30", v: "RAFT kits approved (by Nov 2025) + new approvals Aug 2026", ref: "[6][8][9]" },
];

export const NEEDS = [
  "Field enforcement: Food Safety Officers need rapid, quantitative / semi-quantitative tools for raids and market surveys.",
  "Supply chain: dairy cooperatives, FPOs and small manufacturers need low-cost, high-frequency testing.",
  "Consumers: home tests (DART book, Magic Box) are qualitative, single-adulterant, and their reagents degrade.",
  "Logistics: lab testing needs cold chain, packaging and chain-of-custody documentation.",
];

/* ------------------------------------------------------------------ */
/* Foods                                                               */
/* ------------------------------------------------------------------ */

export type FoodId = "milk" | "turmeric" | "mustard" | "honey" | "dal" | "ghee" | "chilli";

export type ScopeStatus = "prototype" | "candidate" | "context";

export const SCOPE_LABEL: Record<ScopeStatus, string> = {
  prototype: "Prototype target",
  candidate: "Candidate — chemistry not detailed",
  context: "Context only — outside prototype scope",
};

export interface Food {
  id: FoodId;
  name: string;
  adulterants: string[];
  healthRisk: string;
  riskLevel: string;
  scope: ScopeStatus;
  scopeNote: string;
  targets: TargetId[]; // prototype targets from section 4
  color: string;
}

export const FOODS: Food[] = [
  {
    id: "milk",
    name: "Milk",
    adulterants: ["Water", "Urea", "Detergent", "Starch", "Synthetic milk (caustic soda, urea, oil)", "Hydrogen peroxide (preservative)"],
    healthRisk: "Kidney damage, toxicity",
    riskLevel: "High",
    scope: "prototype",
    scopeNote: "Four of the five recommended prototype targets are milk adulterants.",
    targets: ["urea", "detergent", "starch", "h2o2"],
    color: "#f4f1ea",
  },
  {
    id: "turmeric",
    name: "Turmeric",
    adulterants: ["Lead chromate", "Metanil yellow", "Chalk powder"],
    healthRisk: "Lead poisoning (neurotoxin), carcinogenic",
    riskLevel: "Critical",
    scope: "prototype",
    scopeNote: "Lead chromate is singled out in the research as the most dangerous adulterant.",
    targets: ["leadchromate"],
    color: "#e2a51d",
  },
  {
    id: "mustard",
    name: "Mustard oil",
    adulterants: ["Argemone oil"],
    healthRisk: "Epidemic dropsy, liver damage",
    riskLevel: "Critical",
    scope: "candidate",
    scopeNote:
      "Listed as a suitable target (colorimetric tests exist) but the research gives no chemistry, range or time — so no simulated test is offered.",
    targets: [],
    color: "#d7b43a",
  },
  {
    id: "honey",
    name: "Honey",
    adulterants: ["Sugar syrup (C4 sugars)", "Rice syrup"],
    healthRisk: "Fraud, metabolic issues",
    riskLevel: "High (77% adulteration in CSE 2020 study)",
    scope: "candidate",
    scopeNote: "Noted as high-fraud but 'more complex chemistry' — not in the initial five.",
    targets: [],
    color: "#c9801c",
  },
  {
    id: "dal",
    name: "Toor / Moong dal",
    adulterants: ["Kesari dal (Lathyrus sativus)", "Metanil yellow"],
    healthRisk: "Lathyrism (paralysis), carcinogenic",
    riskLevel: "High",
    scope: "context",
    scopeNote: "Appears in the problem analysis only; no detection method proposed.",
    targets: [],
    color: "#e8c35a",
  },
  {
    id: "ghee",
    name: "Ghee",
    adulterants: ["Vanaspati", "Refined oil", "Animal fat"],
    healthRisk: "Trans fats, fraud",
    riskLevel: "Moderate–High",
    scope: "context",
    scopeNote: "Commercial RAFT oil kits cover vanaspati in ghee; not part of this prototype.",
    targets: [],
    color: "#f0d27a",
  },
  {
    id: "chilli",
    name: "Chilli powder",
    adulterants: ["Brick powder", "Sudan dyes", "Artificial red dye"],
    healthRisk: "Carcinogenic dyes",
    riskLevel: "High",
    scope: "context",
    scopeNote: "Appears in the problem analysis only; no detection method proposed.",
    targets: [],
    color: "#b3261e",
  },
];

/* ------------------------------------------------------------------ */
/* Prototype targets (section 4 of the research)                       */
/* ------------------------------------------------------------------ */

export type TargetId = "urea" | "detergent" | "starch" | "h2o2" | "leadchromate";

/** Which nano-scene engine best represents the chemistry. */
export type NanoMode = "agnp" | "aggo" | "starch" | "btb" | "guaiacol" | "dithizone";

export interface Method {
  id: string;
  name: string;
  chemistry: string;
  nanomaterial: string;
  signal: string;
  time: string;
  nanoMode: NanoMode;
  kind: "colorimetric" | "electrochemical";
  /** Color progression used by simulations (illustrative). */
  colorFrom: string;
  colorTo: string;
  lit?: string;
}

export interface Target {
  id: TargetId;
  name: string;
  formula: string;
  food: FoodId;
  foodLabel: string;
  healthConcern: string;
  healthNote: string;
  methods: Method[];
  range: string;
  rangeMin: number;
  rangeMax: number;
  unit: string;
  time: string;
  equipment: string;
  difficulty: string;
  difficultyLevel: number; // 1..5 for meters
  risk: string;
  /** Threshold the simulated verdict is compared against. */
  threshold: { value: number; label: string; kind: "limit" | "lower-bound" };
  /** Typical 'clean' value used when the demo simulates an unadulterated sample. */
  cleanValue: number;
  adulteratedValue: number;
  extra?: string[];
}

export const TARGETS: Target[] = [
  {
    id: "urea",
    name: "Urea",
    formula: "CO(NH₂)₂",
    food: "milk",
    foodLabel: "Toned / full-cream milk",
    healthConcern: "Kidney damage, toxicity",
    healthNote: "Health risk listed in the research for loose-milk adulterants as a group.",
    methods: [
      {
        id: "urea-agnp",
        name: "AgNP colorimetry",
        chemistry: "Citrate-capped AgNPs aggregate → SPR shift, yellow → blue (p-DMAB → yellow is the FSSAI method alternative)",
        nanomaterial: "Citrate-capped AgNPs (green synthesis possible)",
        signal: "Color change (visual / smartphone)",
        time: "< 2 min (colorimetric)",
        nanoMode: "agnp",
        kind: "colorimetric",
        colorFrom: "#e9c64a",
        colorTo: "#5b6f9e",
        lit: "Citrate-AgNPs for urea in milk: LOD 5.56 µM, linear 1–15 mM, < 5 min [10]",
      },
      {
        id: "urea-aggo",
        name: "Ag/GO electrochemistry",
        chemistry: "Non-enzymatic oxidation of urea on an Ag/GO-modified electrode",
        nanomaterial: "Ag/GO composite",
        signal: "Current increase",
        time: "< 30 s (electrochemical)",
        nanoMode: "aggo",
        kind: "electrochemical",
        colorFrom: "#1b2530",
        colorTo: "#4fe3c1",
        lit: "Ag/GO non-enzymatic urea sensor: LOD 0.11 mM, linear 1–10 mM, 36.8 µA/mM [14]",
      },
    ],
    range: "1–15 mM",
    rangeMin: 1,
    rangeMax: 15,
    unit: "mM",
    time: "< 2 min colorimetric · < 30 s electrochemical",
    equipment: "None (visual) or smartphone · Arduino/ESP32 potentiostat (~₹800) for electrochemical",
    difficulty: "Low–Medium",
    difficultyLevel: 2.5,
    risk: "Milk-protein fouling (electrochemical); nanoparticle stability",
    threshold: { value: 11.6, label: "FSSAI-permitted limit ≤ 70 mg/dL (11.6 mM)", kind: "limit" },
    cleanValue: 4.5,
    adulteratedValue: 13.2,
    extra: ["Normal milk: 3–6 mM · adulterated: > 11.6 mM"],
  },
  {
    id: "detergent",
    name: "Detergent",
    formula: "Surfactant (alkaline)",
    food: "milk",
    foodLabel: "Milk",
    healthConcern: "Kidney damage, toxicity",
    healthNote: "Health risk listed in the research for loose-milk adulterants as a group.",
    methods: [
      {
        id: "det-btb",
        name: "Indicator colorimetry",
        chemistry: "Bromothymol blue (or similar pH indicator) → blue; AgNP aggregation is an alternative",
        nanomaterial: "AgNPs or paper-immobilized indicator",
        signal: "Blue color intensity",
        time: "15–30 s",
        nanoMode: "btb",
        kind: "colorimetric",
        colorFrom: "#c9cf6a",
        colorTo: "#2f6fc4",
      },
    ],
    range: "0.05–1.0 % (v/v)",
    rangeMin: 0.05,
    rangeMax: 1.0,
    unit: "% v/v",
    time: "15–30 s",
    equipment: "Smartphone or visual",
    difficulty: "Low",
    difficultyLevel: 1.5,
    risk: "False positives from natural milk pH variation",
    threshold: { value: 0.05, label: "Lower bound of stated detection range (0.05 % v/v)", kind: "lower-bound" },
    cleanValue: 0,
    adulteratedValue: 0.4,
  },
  {
    id: "starch",
    name: "Starch",
    formula: "(C₆H₁₀O₅)ₙ",
    food: "milk",
    foodLabel: "Milk",
    healthConcern: "Kidney damage, toxicity",
    healthNote: "Health risk listed in the research for loose-milk adulterants as a group.",
    methods: [
      {
        id: "starch-iodine",
        name: "Iodine–KI test",
        chemistry: "Iodine–potassium iodide forms a blue-black complex with starch",
        nanomaterial: "Not required (paper microfluidics used for integration)",
        signal: "Blue-black color",
        time: "< 1 min",
        nanoMode: "starch",
        kind: "colorimetric",
        colorFrom: "#d9b36a",
        colorTo: "#1c2146",
      },
    ],
    range: "0.1–2.0 %",
    rangeMin: 0.1,
    rangeMax: 2.0,
    unit: "%",
    time: "< 1 min",
    equipment: "Visual / smartphone",
    difficulty: "Very Low",
    difficultyLevel: 1,
    risk: "None significant (per research)",
    threshold: { value: 0.1, label: "Lower bound of stated detection range (0.1 %)", kind: "lower-bound" },
    cleanValue: 0,
    adulteratedValue: 0.9,
  },
  {
    id: "h2o2",
    name: "Hydrogen peroxide",
    formula: "H₂O₂",
    food: "milk",
    foodLabel: "Milk",
    healthConcern: "Kidney damage, toxicity",
    healthNote: "Used as a preservative. Health risk listed in the research for loose-milk adulterants as a group.",
    methods: [
      {
        id: "h2o2-guaiacol",
        name: "Peroxidase colorimetry",
        chemistry: "Guaiacol + peroxidase → red tetraguaiacol; AgNP oxidation is an alternative",
        nanomaterial: "AgNPs or enzyme-paper",
        signal: "Red color",
        time: "1–2 min",
        nanoMode: "guaiacol",
        kind: "colorimetric",
        colorFrom: "#efe6d6",
        colorTo: "#9b2a1f",
      },
    ],
    range: "0.03–1.0 %",
    rangeMin: 0.03,
    rangeMax: 1.0,
    unit: "%",
    time: "1–2 min",
    equipment: "Smartphone / visual",
    difficulty: "Low–Medium",
    difficultyLevel: 2.5,
    risk: "Enzyme stability (if using peroxidase)",
    threshold: { value: 0.03, label: "Lower bound of stated detection range (0.03 %)", kind: "lower-bound" },
    cleanValue: 0,
    adulteratedValue: 0.35,
  },
  {
    id: "leadchromate",
    name: "Lead chromate",
    formula: "PbCrO₄",
    food: "turmeric",
    foodLabel: "Turmeric powder + water extract",
    healthConcern: "Lead poisoning (neurotoxin); Group 1 carcinogen",
    healthNote: "Linked to documented childhood lead poisoning in Bengal and Bihar.",
    methods: [
      {
        id: "pb-dithizone",
        name: "Dithizone colorimetry",
        chemistry: "Dithizone forms a red complex with lead; FSSAI DART water test (lead chromate settles) is the simple alternative",
        nanomaterial: "AuNPs functionalized with dithizone (advanced)",
        signal: "Red color (dithizone) or sediment (visual)",
        time: "1–5 min",
        nanoMode: "dithizone",
        kind: "colorimetric",
        colorFrom: "#3f6b4a",
        colorTo: "#b3262a",
      },
    ],
    range: "10–100 ppm",
    rangeMin: 10,
    rangeMax: 100,
    unit: "ppm",
    time: "1–5 min",
    equipment: "Visual / smartphone",
    difficulty: "Medium",
    difficultyLevel: 3.5,
    risk: "Lead toxicity — gloves and fume hood; dithizone handling requires care",
    threshold: { value: 10, label: "Lower bound of stated range (10 ppm, health-risk threshold band 10–100 ppm)", kind: "lower-bound" },
    cleanValue: 0,
    adulteratedValue: 48,
  },
];

export const getTarget = (id: TargetId) => TARGETS.find((t) => t.id === id)!;
export const getFood = (id: FoodId) => FOODS.find((f) => f.id === id)!;

/** Candidates mentioned in the research without enough detail to simulate. */
export const CANDIDATES = [
  {
    name: "Argemone oil",
    food: "Mustard oil",
    healthConcern: "Epidemic dropsy, liver damage",
    note: "Research: 'colorimetric tests exist' — method, range and time not specified.",
  },
  {
    name: "Sugar syrup",
    food: "Honey",
    healthConcern: "Fraud, metabolic issues",
    note: "Research: high fraud rate but 'more complex chemistry'.",
  },
];

/* ------------------------------------------------------------------ */
/* Nanomaterials (section 6)                                           */
/* ------------------------------------------------------------------ */

export type NanoId = "agnp" | "aunp" | "go" | "aggo" | "zno";

export interface Nanomaterial {
  id: NanoId;
  name: string;
  short: string;
  synthesis: string;
  role: string;
  cost: string;
  protocol?: string[];
  usedFor: string;
  mechanism: string;
  inScope: boolean;
  nanoMode?: NanoMode;
  sequence: [string, string, string, string];
}

export const NANOMATERIALS: Nanomaterial[] = [
  {
    id: "agnp",
    name: "Silver nanoparticles",
    short: "AgNPs",
    synthesis: "Green synthesis (plant extract + AgNO₃, UV / sunlight)",
    role: "Colorimetric (SPR shift), electrocatalytic (urea oxidation)",
    cost: "₹500–1,000 (chemicals for 100 mL)",
    protocol: [
      "Mix 1 mM AgNO₃ with plant extract (e.g. neem, tulsi) 1:9 v/v",
      "Expose to sunlight / UV 2–4 h → yellow-brown color",
      "Characterize: UV-Vis peak ~420 nm (if spectrophotometer available)",
      "Use directly for colorimetric assays or deposit on paper",
    ],
    usedFor: "Urea (colorimetric); alternative for detergent and H₂O₂",
    mechanism:
      "Ag/Au nanoparticles absorb strongly in the visible range (surface plasmon resonance). Analyte-induced aggregation shifts the absorption peak → a visible color change.",
    inScope: true,
    nanoMode: "agnp",
    sequence: ["Urea approaches dispersed AgNPs", "Citrate-capped AgNP surface", "Aggregation shifts SPR peak", "Yellow → blue color read by camera"],
  },
  {
    id: "aunp",
    name: "Gold nanoparticles",
    short: "AuNPs",
    synthesis: "Citrate reduction (Turkevich method)",
    role: "Colorimetric (aggregation-based), electrode modifier",
    cost: "₹2,000–5,000 (HAuCl₄ expensive)",
    usedFor: "Lead (dithizone-functionalized AuNPs — advanced)",
    mechanism:
      "Aggregation of AuNPs changes their plasmon absorption (e.g. red → blue). Functionalized with dithizone, they are proposed for lead detection.",
    inScope: true,
    nanoMode: "dithizone",
    sequence: ["Pb²⁺ from turmeric extract", "Dithizone-functionalized AuNP", "Lead–dithizone complex forms", "Red color read by camera"],
  },
  {
    id: "go",
    name: "Graphene oxide",
    short: "GO",
    synthesis: "Hummers' method (or buy)",
    role: "Electrode modifier (enhances electron transfer), immobilization matrix",
    cost: "₹1,000–3,000 / g (commercial)",
    usedFor: "Electrode modification; anchoring enzymes / aptamers",
    mechanism:
      "GO's large surface area and –COOH / –OH functional groups anchor enzymes and aptamers stably, and enhance electron transfer at the electrode.",
    inScope: true,
    nanoMode: "aggo",
    sequence: ["Analyte reaches electrode", "GO sheet with –COOH / –OH groups", "Faster electron transfer", "Current read by ADC"],
  },
  {
    id: "aggo",
    name: "Silver / graphene oxide composite",
    short: "Ag/GO",
    synthesis: "Chemical reduction of Ag⁺ on GO sheets",
    role: "Non-enzymatic urea sensor (synergistic catalysis)",
    cost: "₹1,500–2,500 (combined)",
    protocol: [
      "Disperse GO (2 mg/mL) in water, sonicate 30 min",
      "Add AgNO₃ (1:5 w/w Ag:GO), stir 1 h",
      "Add NaBH₄ (reducing agent) dropwise → black precipitate",
      "Wash, dry, redisperse for electrode coating",
    ],
    usedFor: "Urea (electrochemical, non-enzymatic)",
    mechanism: "Ag/GO lowers the overpotential for urea oxidation → higher current at lower voltage.",
    inScope: true,
    nanoMode: "aggo",
    sequence: ["Urea diffuses to electrode", "Ag/GO-modified electrode", "Urea oxidised → electrons released", "Current ∝ concentration → ADS1115"],
  },
  {
    id: "zno",
    name: "Zinc oxide nanoparticles",
    short: "ZnO",
    synthesis: "Sol-gel (zinc acetate + NaOH)",
    role: "Chemiresistive (formaldehyde gas), photocatalytic",
    cost: "₹500–1,000",
    usedFor: "Formaldehyde vapor (fish) — gas phase, outside this prototype",
    mechanism: "Analyte adsorption changes the resistance of metal-oxide nanostructures; needs heating (80–350 °C).",
    inScope: false,
    sequence: ["", "", "", ""],
  },
];

/* ------------------------------------------------------------------ */
/* Hardware (section 5)                                                */
/* ------------------------------------------------------------------ */

export interface BomItem {
  id: string;
  component: string;
  part: string;
  price: string;
  notes: string;
  optional?: boolean;
}

export const BOM: BomItem[] = [
  { id: "mcu", component: "Microcontroller", part: "ESP32 DevKit v1 (30-pin)", price: "₹500–600", notes: "Wi-Fi/BT, dual-core, 18 ADC channels" },
  { id: "cam", component: "Camera (optional)", part: "ESP32-CAM (OV2640)", price: "₹735–950", notes: "Image-based colorimetry; can also use phone", optional: true },
  { id: "led", component: "LEDs", part: "5 mm white + RGB (5 pcs)", price: "₹50", notes: "Illumination / excitation" },
  { id: "pd", component: "Photodiode", part: "BPW34 or TEMT6000", price: "₹30–100", notes: "Absorbance measurement" },
  { id: "adc", component: "ADC (if needed)", part: "ADS1115 (16-bit, 4-ch)", price: "₹250", notes: "High-resolution electrochemical readout" },
  { id: "spce", component: "Electrodes (electrochemical mode)", part: "Screen-printed carbon electrodes (SPCE)", price: "₹100–200 / pc", notes: "Reusable 10–20 times" },
  { id: "oled", component: "Display", part: '0.96" OLED I²C (128×64)', price: "₹200", notes: "Standalone readout" },
  { id: "bat", component: "Battery", part: "18650 Li-ion (2000 mAh) + TP4056 charger", price: "₹300", notes: "2–3 days standby" },
  { id: "comm", component: "Communication", part: "ESP32 built-in Wi-Fi / BT", price: "Included", notes: "Send data to phone / cloud" },
  { id: "cart", component: "Cartridge", part: "Whatman Grade 4 filter paper + 3D-printed holder", price: "₹12 + ₹50 (holder)", notes: "Reusable holder, disposable strip" },
  { id: "enc", component: "Enclosure", part: "3D-printed PLA (100 g)", price: "₹200–300", notes: "Custom design" },
];

export const BOM_TOTAL = "₹2,500–3,500 (excluding smartphone)";

export const CARTRIDGE = {
  size: "2 cm × 6 cm paper strip",
  zones: "4–6 test zones",
  volume: "50–100 µL (dropper included)",
  holder: "3D-printed, inclined geometry for gravity-assisted flow (as in the IIT Kharagpur patent)",
  reagents: [
    { target: "urea" as TargetId, reagent: "p-DMAB or AgNP solution (dried)" },
    { target: "detergent" as TargetId, reagent: "Bromothymol blue" },
    { target: "starch" as TargetId, reagent: "Iodine–KI" },
    { target: "h2o2" as TargetId, reagent: "Guaiacol + peroxidase (or AgNPs)" },
  ],
  controls: ["Negative control zone (false-positive mitigation)", "Reference color patch (calibration-drift mitigation; app auto-calibrates per session)"],
  storage: "Lyophilize reagents on paper; store in desiccator",
};

export const DATA_PROCESSING = [
  { mode: "Image-based", text: "Smartphone app (OpenCV) extracts RGB / grayscale from test zones; calibration curve → concentration." },
  { mode: "Electrochemical", text: "ESP32 reads current via ADS1115; maps to concentration." },
  { mode: "Output", text: "Pass / Fail (vs FSSAI limits) + numeric value; log to Google Sheets / ThingSpeak." },
];

/* ------------------------------------------------------------------ */
/* Technology landscape (section 2)                                    */
/* ------------------------------------------------------------------ */

export interface Tech {
  name: string;
  principle: string;
  targets: string;
  performance: string[];
  cost: string;
  limitations: string;
  feasibility: string;
  feasibilityLevel: number; // 1..5
}

export const TECHNOLOGIES: Tech[] = [
  {
    name: "Colorimetric nanoparticle sensors",
    principle: "Analyte induces aggregation or SPR shift in Au/Ag NPs → visible color change",
    targets: "Urea, melamine, formaldehyde, pesticides, heavy metals",
    performance: ["Citrate-AgNPs urea in milk: LOD 5.56 µM, 1–15 mM, < 5 min", "Au/AgNPs melamine: LOD 5.08–13.33 µM", "AgNPs + UV-Vis urea: R² > 0.90 vs FSSAI DMAB method"],
    cost: "Synthesis ₹500–2,000; < ₹10/test if paper-immobilized",
    limitations: "Matrix interference (milk proteins), colloid stability, batch variability",
    feasibility: "High",
    feasibilityLevel: 5,
  },
  {
    name: "Metal-oxide chemiresistive",
    principle: "Analyte adsorption changes resistance of ZnO, SnO₂, WO₃ nanostructures",
    targets: "Formaldehyde (fish), VOCs, biogenic amines",
    performance: ["Sub-ppm formaldehyde; 80–350 °C operation"],
    cost: "Moderate; needs heater + resistance circuit",
    limitations: "High-temperature operation, humidity cross-sensitivity, poor fit for liquids",
    feasibility: "Medium",
    feasibilityLevel: 3,
  },
  {
    name: "Graphene / carbon electrochemical",
    principle: "GO / rGO / CNTs enhance electron transfer; analyte redox → current change",
    targets: "Urea, pesticides, food additives",
    performance: ["Ag/GO urea: LOD 0.11 mM, 1–10 mM, 36.8 µA/mM", "Graphene-Au: µM–nM LODs"],
    cost: "GO/CNT ₹1,000–5,000/g; SPE ₹50–200 each",
    limitations: "Needs potentiostat / custom circuit; surface fouling",
    feasibility: "Medium–High",
    feasibilityLevel: 4,
  },
  {
    name: "Paper microfluidics (µPADs)",
    principle: "Capillary flow through paper channels with pre-loaded reagents",
    targets: "Urea, starch, detergent, H₂O₂, neutralizers, boric acid (milk)",
    performance: ["IIT Kharagpur 2025: LOD 0.03 % (urea, H₂O₂)", "15–60 s urea/detergent; ~2 min others"],
    cost: "₹12/strip + ₹8.5 holder = ₹21 kit",
    limitations: "Semi-quantitative without image analysis; reagent stability",
    feasibility: "Very High",
    feasibilityLevel: 5,
  },
  {
    name: "Lateral-flow assays",
    principle: "Antibody / aptamer capture on nitrocellulose; line intensity",
    targets: "Pathogens, allergens, some toxins",
    performance: ["LOD ~5–50 CFU/mL (pathogens); 10–30 min"],
    cost: "₹200–1,000/test commercial",
    limitations: "Expensive biorecognition, cold storage, single-use",
    feasibility: "Low–Medium",
    feasibilityLevel: 2,
  },
  {
    name: "Smartphone optical detection",
    principle: "Phone camera captures color / fluorescence; app analyzes RGB",
    targets: "Any colorimetric / fluorometric assay",
    performance: ["Pesticides: LOD ~0.89 µg/kg (median of 5 studies)"],
    cost: "Phone owned; 3D-printed clip ~₹200",
    limitations: "Ambient light variability; calibration needed",
    feasibility: "High",
    feasibilityLevel: 5,
  },
  {
    name: "Electrochemical biosensors",
    principle: "Urease hydrolyzes urea → NH₃ + CO₂ → pH/potential change; aptamer binding → impedance",
    targets: "Urea, melamine, pesticides",
    performance: ["Urease electrochemical: LOD 5.0 µM, stable 28 days", "Melamine aptasensor: LOD 0.1 ppm (AuNP amplified)"],
    cost: "Enzymes / aptamers ₹2,000–10,000",
    limitations: "Enzyme stability (temperature, pH), cost",
    feasibility: "Medium",
    feasibilityLevel: 3,
  },
  {
    name: "Spectroscopy (NIR, Raman, FTIR)",
    principle: "Molecular fingerprinting + chemometrics",
    targets: "Melamine, sucrose / ammonium sulfate in milk, oils",
    performance: ["Portable Raman: LOD 50–1000 ppm", "NIR + LS-SVM: 100 % melamine detection in milk powder"],
    cost: "Handheld ₹50,000–5,00,000",
    limitations: "Expensive; needs calibration models",
    feasibility: "Low",
    feasibilityLevel: 1,
  },
];

export const PROTOTYPES = [
  { name: "IIT Kharagpur µPAD (2025)", targets: "Urea, starch, detergent, H₂O₂, neutralizer, boric acid (milk)", tech: "Paper microfluidics + colorimetry", lod: "0.03 % (urea, H₂O₂)", time: "15–120 s", cost: "₹21 / kit", limits: "Semi-quantitative, reagent stability" },
  { name: "Ag/GO urea sensor (2026)", targets: "Urea (water, milk)", tech: "Non-enzymatic electrochemical", lod: "0.11 mM", time: "< 1 min", cost: "₹200–500 (electrode)", limits: "Needs potentiostat; protein fouling in milk" },
  { name: "Smartphone pesticide sensor (2023–25)", targets: "Malathion, organophosphates", tech: "α-CD-AuNPs + phone camera", lod: "~0.89 µg/kg (median)", time: "5–10 min", cost: "₹500–1,000 (reagents)", limits: "Calibration, light control" },
  { name: "Portable Raman (2025)", targets: "Sucrose, melamine, urea in milk", tech: "Fiber-optic Raman + Al wells", lod: "50–1000 ppm", time: "< 1 min", cost: "₹2–5 lakh (device)", limits: "Expensive, needs chemometrics" },
  { name: "Melamine aptasensor (2024)", targets: "Melamine (milk)", tech: "AuNP-amplified aptasensor", lod: "0.1 ppm", time: "10–20 min", cost: "₹1,000–2,000", limits: "Aptamer cost, stability" },
];

export const RAFT = {
  approved: "88 RAFT kits approved (as of Nov 2025); 30 new kits approved Aug 2026 for milk, oils, water, meat, fish",
  examples: ["Milk kits: urea, starch, detergent, H₂O₂, neutralizers", "Oil kits: argemone oil, vanaspati in ghee", "Spice kits: lead chromate in turmeric, metanil yellow"],
  price: "₹1,500–15,000 per kit (50–100 tests)",
  perTest: "₹30–300 per test",
  limits: "Proprietary reagents, limited to specific adulterants",
};

/* ------------------------------------------------------------------ */
/* Plan, risks, novelty                                                */
/* ------------------------------------------------------------------ */

export const ROADMAP = [
  { phase: "Literature + reagent sourcing", when: "Month 1", m: [1, 1], text: "Finalize targets; order chemicals (AgNO₃, p-DMAB, iodine…); synthesize AgNPs." },
  { phase: "Proof-of-concept (colorimetric)", when: "Months 2–3", m: [2, 3], text: "Validate urea / detergent / starch detection in milk (visual + smartphone)." },
  { phase: "Cartridge fabrication", when: "Months 4–5", m: [4, 5], text: "Design 3D holder; load reagents on paper; test flow and reproducibility." },
  { phase: "Electronics integration", when: "Months 6–7", m: [6, 7], text: "Build ESP32 + photodiode / ADS1115 circuit; develop app (MIT App Inventor / Flutter)." },
  { phase: "Calibration + validation", when: "Months 8–9", m: [8, 9], text: "Test on 50+ milk samples (spiked + real); compare with FSSAI lab results." },
  { phase: "Iterate + document", when: "Months 10–12", m: [10, 12], text: "Optimize LOD and stability; write paper / patent; prepare demo." },
];
export const BUDGET = "₹10,000–20,000 (chemicals, electronics, 3D printing)";

export const RISKS = [
  { risk: "Matrix interference (milk proteins)", mitigation: "Sample dilution (1:2 with water) or protein precipitation (acetonitrile)" },
  { risk: "Nanoparticle stability", mitigation: "Store at 4 °C; use within 2 weeks; add stabilizer (PVP, citrate)" },
  { risk: "False positives", mitigation: "Negative control zone on strip; multi-parameter logic (e.g. urea + detergent together)" },
  { risk: "Reagent degradation", mitigation: "Lyophilize reagents on paper; store in desiccator" },
  { risk: "Calibration drift", mitigation: "Reference color patch on strip; app auto-calibrates per session" },
];

export const NOVELTY = [
  { title: "Multi-adulterant cartridge", text: "Several targets in a single cartridge, vs single-target RAFT kits." },
  { title: "Open-source hardware & software", text: "Versus proprietary RAFT devices." },
  { title: "Smartphone quantification", text: "Quantification and data logging, vs visual-only DART tests." },
  { title: "Low cost target", text: "Research goal: < ₹20 per test consumables (vs ₹30–300 for commercial kits)." },
  { title: "Reproducible nanomaterials", text: "Green-synthesized AgNPs that students can make, vs expensive commercial nanoparticles." },
];

/** Things in the research that do not agree with each other — shown openly. */
export const OPEN_QUESTIONS = [
  "The component table totals ₹2,500–3,500 for the device BOM, while the novelty section states '< ₹500 device'. The BOM figure is used on this site; the < ₹500 figure is treated as an aspirational target.",
  "FSSAI 2024–25 is summarised as '~20 % non-conforming'; unsafe + substandard counts alone give ≈ 17.9 % of 170,535 samples.",
  "The FSSAI urea limit (11.6 mM) sits just above the reported Ag/GO linear range (1–10 mM), so the electrochemical mode would need its range extended, or the sample diluted, to make a clean pass/fail call at the limit.",
  "Nothing on this page has been measured by the project yet. All performance values are literature benchmarks for similar sensors.",
];

/* ------------------------------------------------------------------ */
/* References                                                          */
/* ------------------------------------------------------------------ */

export const REFERENCES: { n: number; url: string; label: string }[] = [
  { n: 1, label: "The Hindu — food adulteration, milk safety", url: "https://www.thehindu.com/society/food-adulteration-india-milk-safety/article71468235.ece" },
  { n: 2, label: "Organic Mandya — food adulteration in India", url: "https://know.organicmandya.com/know-your-food/adulteration-in-india/food-adulteration-india/" },
  { n: 3, label: "India Today — ghee to paneer adulteration (2025)", url: "https://www.indiatoday.in/india-today-insight/story/ghee-to-paneer-how-food-adulteration-thrives-in-india-2819262-2025-11-13" },
  { n: 4, label: "PMC12512190", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12512190/" },
  { n: 5, label: "AIP Conference Proceeding (Scribd)", url: "https://www.scribd.com/document/869372337/AIP-Confrence-Proceeding" },
  { n: 6, label: "PIB press release 2292341", url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2292341&reg=3&lang=1" },
  { n: 7, label: "ANI — FSSAI initiatives to curb adulteration", url: "https://www.aninews.in/news/business/indias-food-regulation-authority-fssai-launches-initiatives-to-curb-food-adulteration20240404204027/" },
  { n: 8, label: "PIB press release 2292341 (reg 6)", url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2292341&reg=6&lang=1" },
  { n: 9, label: "FnB News — FSSAI nod to 30 rapid testing kits", url: "http://www.fnbnews.com/Top-News/fssai-gives-nod-to-30-rapid-food-testing-kits-across-six-categories-53662" },
  { n: 10, label: "Biosensors 16:92 — table 1 (PMC12937801)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12937801/table/biosensors-16-00092-t001/" },
  { n: 11, label: "LWT S0023643822008283 (Scribd)", url: "https://www.scribd.com/document/946904861/1-s2-0-S0023643822008283-main" },
  { n: 12, label: "PMC13511230", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC13511230/" },
  { n: 13, label: "PubMed 41668622", url: "https://pubmed.ncbi.nlm.nih.gov/41668622/" },
  { n: 14, label: "Catalysts 16(5):381 — Ag/GO urea sensor", url: "https://www.mdpi.com/2073-4344/16/5/381" },
  { n: 15, label: "Food Bioengineering fbe2.70035", url: "https://onlinelibrary.wiley.com/doi/10.1002/fbe2.70035" },
  { n: 16, label: "J. Food Meas. Charact. s11694-026-04745-5", url: "https://link.springer.com/article/10.1007/s11694-026-04745-5" },
  { n: 17, label: "Portable paper-based microfluidic device for milk adulterants (IIT Kharagpur)", url: "https://www.scribd.com/document/935824231/Portable-paper-based-microfluidic-device-for-rapid-on-site-screening-of-milk-adulterants" },
  { n: 18, label: "Sensing & Imaging s11220-025-00580-y", url: "https://studylib.net/doc/28938248/s11220-025-00580-y" },
  { n: 19, label: "PMC12971809", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12971809/" },
  { n: 20, label: "PMC12467590", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12467590/" },
  { n: 21, label: "PMC13115446 — smartphone sensing", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC13115446/" },
  { n: 22, label: "SciLTP nenp 2606004345", url: "https://www.sciltp.com/journals/nenp/articles/2606004345" },
  { n: 23, label: "Micromachines 17(7):821", url: "https://www.mdpi.com/2072-666X/17/7/821" },
  { n: 24, label: "Probots — ESP32 30-pin dev board", url: "https://probots.co.in/esp32-30-pin-cp2102-development-board.html" },
  { n: 25, label: "Price history — ESP32-CAM OV3660", url: "https://pricehistory.app/p/esp32-cam-development-board-wifi-bluetooth-ov3660-utwfdCIm" },
  { n: 26, label: "Price history — ESP32-CAM OV2640", url: "https://pricehistory.app/p/esp32-cam-development-board-wifi-bluetooth-ov2640-8fKYwlw8" },
  { n: 27, label: "PMC12665647", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12665647/" },
  { n: 28, label: "J. Anal. Chem. 355763", url: "https://journals.rcsi.science/0044-4502/article/view/355763" },
  { n: 29, label: "PMC12691711", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12691711/" },
];
